### ISSUE TITLE
Slight duplication in sentence in blog post for release 1.5

### ISSUE THREAD

**Issue by Coderambling** [holoviz-dev/blog#67]
The sentence under the Release heading in the doc has some duplication @philippjfr .

Current:

 "While technically a minor release, this minor release hugely expands the scope of what is possible in Panel."

Better (shorter and clearer):

"While technically a minor release, _it_ hugely expands the scope of what is possible in Panel."

https://github.com/holoviz-dev/blog/blob/b5b39b703db311ad09783ca36d1188bf987bd0d1/posts/panel_release_1.5/index.ipynb#L1231

**Comment by philippjfr** [comment]
Thanks, I believe @jbednar's edit suggestions had addressed these.
