### ISSUE TITLE
Improvement suggestions for blog post for release 1.5

### ISSUE THREAD

**Issue by Coderambling** [holoviz-dev/blog#68]
Minor improvement suggestions @philippjfr .

Current:

Specifically they introduced...

Suggestion:

Specifically, import and export specifiers were introduced.

At the end of the sentence, it says:

Current:

...for the consumption of others.

But for what others? Other libraries, other ESM components, ... ?

https://github.com/holoviz-dev/blog/blob/b5b39b703db311ad09783ca36d1188bf987bd0d1/posts/panel_release_1.5/index.ipynb#L1256C97-L1256C97

**Comment by philippjfr** [comment]
Thanks, I believe @MarcSkovMadsen's edits addressed these.
